### ISSUE TITLE
运行SQL脚本失败

### ISSUE THREAD

**Issue by NBIronman** [cckevincyh/StudentSystem#4]
麻烦问下您。您使用的SQL脚本文件所对应的数据库编码字符集和排列规则方式都是什么？我导入SQL文件每次都是失败。

**Comment by WUQING0** [comment]
utf8和utf8_genci

**Comment by NBIronman** [comment]
![~PKMI6W 5%FSFM8HIT25ZXP](https://user-images.githubusercontent.com/80090145/146645361-cc7afff8-bf9d-4381-a8c9-70ae2b949058.png)
ni'ha你好，我运行SQL后报了这个错，请问下，您能帮看看这个是怎么回事吗？

**Comment by NBIronman** [comment]
我知道了，是Student_Sex那部分，少了一个下划线_

**Comment by shixinyue151** [comment]
添加学生成绩，没有任何反应，也没有可以输入的文本框，是少一段代码吗？
