### ISSUE TITLE
想要帮助2.0

### ISSUE THREAD

**Issue by TuTuHuHuDaShui** [cckevincyh/StudentSystem#6]
您好，我想问一下这个运行之后，注册账号之后没有反应是因为什么呢？

**Comment by cckevincyh** [comment]
> 您好，我想问一下这个运行之后，注册账号之后没有反应是因为什么呢？

后台有报错吗？

**Comment by cckevincyh** [comment]
> 您好，我想问一下这个运行之后，注册账号之后没有反应是因为什么呢？

需要执行StudentSystemDao.sql里面的脚本，看看控制台有没有报错，再看看插入的数据中文有没有问题，可能是字符集没设置对

**Comment by TuTuHuHuDaShui** [comment]
哦哦哦好的谢谢您

**Comment by thisislsm** [comment]
请问一下该怎么解决这个问题阿？我注册和登录控制台都报错不了
